# site settings
title: Thu Blog
subtitle: Writing this and that
email: votthu@yahoo.com
description: Short stories about my life and experiences
baseurl: "/"  # the subpath of your site, e.g. /blog
#baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "thublog.github.io" # the base hostname & protocol for your site
author:
street_address: 1234 Nevermind Road
city: Tulsa
state: NV
zip_code: 31213
country: US
phone: (415) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: #https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
